const DATABASE_NAME = process.env.DATABASE_NAME;
const FIREBASE_URL = process.env.FIREBASE_URL;
const ALLOWED_ORIGINS = [process.env.ALLOWED_CLIENT_URL];
const FIREBASE_CREDENTIALS = process.env.FIREBASE_CREDENTIALS;
const FIREBASE_API_KEY = process.env.FIREBASE_API_KEY;

if (process.env.ALLOWED_EXTRA_CLIENT_URL) {
  ALLOWED_ORIGINS.push(process.env.ALLOWED_EXTRA_CLIENT_URL);
}

module.exports = { FIREBASE_URL, DATABASE_NAME, ALLOWED_ORIGINS, FIREBASE_CREDENTIALS, FIREBASE_API_KEY };
