const DATABASE_NAME = process.env.DATABASE_NAME;
const FIREBASE_URL = process.env.FIREBASE_URL;
const ALLOWED_ORIGINS = [process.env.ALLOWED_CLIENT_URL];
const FIREBASE_CREDENTIALS = process.env.FIREBASE_CREDENTIALS;
const FIREBASE_API_KEY = process.env.FIREBASE_API_KEY;
const CLIENT_ID =  process.env.SLACK_CLIENT_ID;
const CLIENT_SECRET = process.env.SLACK_CLIENT_SECRET;
const REDIRECT_URI = process.env.SLACK_REDIRECT_URI;
const ALLOWED_CLIENT_URL = process.env.ALLOWED_CLIENT_URL;

const OAUTH_URL = 'https://slack.com/api/oauth.access';

if (process.env.ALLOWED_EXTRA_CLIENT_URL) {
  ALLOWED_ORIGINS.push(process.env.ALLOWED_EXTRA_CLIENT_URL);
}

module.exports = {
  CLIENT_ID,
  CLIENT_SECRET,
  REDIRECT_URI,
  FIREBASE_URL,
  DATABASE_NAME,
  ALLOWED_ORIGINS,
  FIREBASE_CREDENTIALS,
  FIREBASE_API_KEY,
  OAUTH_URL,
  ALLOWED_CLIENT_URL
};
